name: Build Docker Image

on:
    workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
      name: wojiaoluyuan/myv2
      username: '${{secrets.wojiaoluyuan}}'
      password: '${{secrets.myv2v2v2v2}}'
